backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/content/homepage.json"
        label: "Hero Section"
        name: "hero"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }

  - name: "about"
    label: "About Section"
    files:
      - file: "src/content/about.json"
        label: "About Info"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }

  - name: "testimonials"
    label: "Testimonials"
    files:
      - file: "src/content/testimonials.json"
        label: "Student Testimonials"
        name: "testimonials"
        fields:
          - label: "Testimonials"
            name: ""
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }
              - { label: "Photo", name: "photo", widget: "image" }

  - name: "gallery"
    label: "Gallery"
    files:
      - file: "src/content/gallery.json"
        label: "Gallery Images"
        name: "gallery"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            field: { label: "Image", name: "", widget: "image" }

  - name: "videos"
    label: "Showcase Videos"
    files:
      - file: "src/content/videos.json"
        label: "Videos"
        name: "videos"
        fields:
          - label: "Showcase Videos"
            name: "showcase_videos"
            widget: "list"
            field: { label: "YouTube Embed URL", name: "", widget: "string" }